Repository mapbox/Hecate, pull requests merged in 2019-10, with the labels that each got.

#191 Session Invalidation
  src/auth/middleware.rs
  src/auth/mod.rs
  src/err/mod.rs
  src/lib.rs
  src/user/token.rs
  web/dist/index.html
  web/dist/main.a8a224f9.js
  web/src/modals/Self.vue
Labels: bug

#193 No Dist
  .circleci/config.yml
  .gitignore
  Cargo.lock
  README.md
  web/.gitignore
  web/dist/assembly.4e53fc76.js
  web/dist/assembly.a18c4902.css
  web/dist/favicon.692d1453.ico
  web/dist/index.html
  web/dist/login/index.html
  web/dist/main.02f5bf51.js
  web/dist/main.a8a224f9.js
  web/dist/mapbox-gl-geocoder.45e809d1.css
Labels: enhancement

#195 DB Error
  Cargo.lock
  src/lib.rs
  src/mvt/mod.rs
  src/worker/mod.rs
Labels: bug

#197 Update Base Deps
  Cargo.lock
  Cargo.toml
Labels: enhancement

#194 Stable rust
  .circleci/config.yml
  README.md
  ci/package-lock.json
  ci/yarn.lock
Labels: enhancement

#199 Filter out duplicates from get bounds call
  Cargo.lock
  release
  src/bounds/mod.rs
Labels: bug

#201 Test Session
  src/auth/middleware.rs
  src/bounds/mod.rs
  src/lib.rs
  tests/user_session.rs
  tests/user_session_closed.rs
  tests/users.rs
Labels: bug, enhancement
